apiVersion: v1
kind: ConfigMap
metadata:
  name: piraeus-node
  namespace: piraeus-system
data:
  INIT_DEBUG: "false"
  LS_CONTROLLERS: piraeus-controller.piraeus-system.svc.cluster.local:3370
  POOL_BASE_DIR: /var/lib/piraeus/storagepools
  DRBD_IMG_REPO: quay.io/piraeusdatastore
  DRBD_IMG_TAG: v9.0.22
  DRBD_IMG_PULL_POLICY: IfNotPresent
  MAP_HOST_LVM: "true"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: piraeus-node
  namespace: piraeus-system
spec:
  minReadySeconds: 0
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: piraeus
      app.kubernetes.io/component: piraeus-node
  template:
    metadata:
      labels:
        app.kubernetes.io/name: piraeus
        app.kubernetes.io/component: piraeus-node
    spec:
      restartPolicy: Always
      hostNetwork: true
      hostPID: true
      hostIPC: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
      - name: init
        image: quay.io/piraeusdatastore/piraeus-init:v0.5.6
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        envFrom:
        - configMapRef:
            name: piraeus-node
        env:
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        args:
        - initNode
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
        - name: init
          mountPath: /init
        - name: dockersock
          mountPath: /var/run/docker.sock
        - name: usr-src
          mountPath: /usr/src
        - name: lib-modules
          mountPath: /lib/modules
        - name: opt-piraeus
          mountPath: /opt/piraeus
        - name: drbd-conf
          mountPath: /etc/drbd.conf
        - name: etc-drbd-d
          mountPath: /etc/drbd.d
      containers:
      - name: satellite
        image: quay.io/piraeusdatastore/piraeus-server:v1.4.2
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
        envFrom:
        - configMapRef:
            name: piraeus-node
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        args:
        - startSatellite
        readinessProbe:
          successThreshold: 3
          failureThreshold: 3
          tcpSocket:
            port: 3366
          periodSeconds: 5
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
        - name: init
          mountPath: /init
        - name: init
          mountPath: /usr/bin/pre-start.sh
          subPath: bin/prestart-node.sh
        - name: log
          mountPath: /var/log/linstor-satellite
        - name: var-lib-piraeus
          mountPath: /var/lib/piraeus
        - name: dev
          mountPath: /dev
        - name: lib-modules
          mountPath: /lib/modules
        - name: var-lib-linstor-d
          mountPath: /var/lib/linstor.d
      volumes:
      - name: timezone
        hostPath:
          path: /usr/share/zoneinfo/Etc/UTC
      - name: init
        emptyDir: {}
      - name: opt-piraeus
        hostPath:
          path: /opt/piraeus
      - name: var-lib-piraeus
        hostPath:
          path: /var/lib/piraeus
      - name: log
        hostPath:
          path: /var/log/piraeus/linstor-satellite
      - name: dev
        hostPath:
          path: /dev
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name: usr-src
        hostPath:
          path: /usr/src
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: drbd-conf
        hostPath:
          path: /etc/drbd.conf
          type: FileOrCreate
      - name: etc-drbd-d
        hostPath:
          path: /etc/drbd.d
      - name: var-lib-linstor-d
        hostPath:
          path: /var/lib/linstor.d
      - name: etc-linstor
        hostPath:
          path: /etc/linstor
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: piraeus/node
                operator: In
                values:
                - "true"
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - key: CriticalAddonsOnly
        operator: Exists
